### ISSUE TITLE
Multiple Credit Memos Throws Critical Error, No Credit Memo Created

### ISSUE THREAD

**Issue by PromInc** [Kount/magento2-kount#26]
## Issue
If the Kount ENS reports more than one order that requires a credit memo in the same request, a critical error is thrown and the credit memos are never created.

The error is reported in `var/log/kount.log`

```
main.CRITICAL: RuntimeException: Registry key "current_creditmemo" already exists in /magento/path/vendor/magento/framework/Registry.php:60
Stack trace:
#0 /magento/path/vendor/magento/module-sales/Controller/Adminhtml/Order/CreditmemoLoader.php(248): Magento\Framework\Registry->register()
#1 /magento/path/vendor/kount/magento2-kount/src/module-kount/Model/Order/Action/Decline.php(162): Magento\Sales\Controller\Adminhtml\Order\CreditmemoLoader->load()
#2 /magento/path/vendor/kount/magento2-kount/src/module-kount/Model/Order/Action/Decline.php(108): Kount\Kount\Model\Order\Action\Decline->orderRefund()
#3 /magento/path/vendor/kount/magento2-kount/src/module-kount/Model/Order/Action/Decline.php(74): Kount\Kount\Model\Order\Action\Decline->refund()
#4 /magento/path/vendor/kount/magento2-kount/src/module-kount/Model/Ens/EventHandler/StatusEdit.php(226): Kount\Kount\Model\Order\Action\Decline->process()
#5 /magento/path/vendor/kount/magento2-kount/src/module-kount/Model/Ens/EventHandler/StatusEdit.php(192): Kount\Kount\Model\Ens\EventHandler\StatusEdit->declineOrder()
#6 /magento/path/vendor/kount/magento2-kount/src/module-kount/Model/Ens/EventHandler/StatusEdit.php(92): Kount\Kount\Model\Ens\EventHandler\StatusEdit->updateOrderStatus()
#7 /magento/path/vendor/kount/magento2-kount/src/module-kount/Model/Ens/Manager.php(133): Kount\Kount\Model\Ens\EventHandler\StatusEdit->process()
#8 /magento/path/vendor/kount/magento2-kount/src/module-kount/Model/Ens/Manager.php(83): Kount\Kount\Model\Ens\Manager->handleEvent()
#9 /magento/path/vendor/kount/magento2-kount/src/module-kount/Controller/Ens/Index.php(89): Kount\Kount\Model\Ens\Manager->handleRequest()
#10 /magento/path/vendor/magento/framework/Interception/Interceptor.php(58): Kount\Kount\Controller\Ens\Index->execute()
#11 /magento/path/vendor/magento/framework/Interception/Interceptor.php(138): Kount\Kount\Controller\Ens\Index\Interceptor->___callParent()
#12 /magento/path/vendor/magento/framework/Interception/Interceptor.php(153): Kount\Kount\Controller\Ens\Index\Interceptor->Magento\Framework\Interception\{closure}()
#13 /magento/path/generated/code/Kount/Kount/Controller/Ens/Index/Interceptor.php(23): Kount\Kount\Controller\Ens\Index\Interceptor->___callPlugins()
#14 /magento/path/vendor/magento/framework/App/Action/Action.php(111): Kount\Kount\Controller\Ens\Index\Interceptor->execute()
#15 /magento/path/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\Action\Action->dispatch()
#16 /magento/path/vendor/magento/framework/Interception/Interceptor.php(138): Kount\Kount\Controller\Ens\Index\Interceptor->___callParent()
#17 /magento/path/vendor/magento/framework/Interception/Interceptor.php(153): Kount\Kount\Controller\Ens\Index\Interceptor->Magento\Framework\Interception\{closure}()
#18 /magento/path/generated/code/Kount/Kount/Controller/Ens/Index/Interceptor.php(32): Kount\Kount\Controller\Ens\Index\Interceptor->___callPlugins()
#19 /magento/path/vendor/magento/framework/App/FrontController.php(245): Kount\Kount\Controller\Ens\Index\Interceptor->dispatch()
#20 /magento/path/vendor/magento/framework/App/FrontController.php(212): Magento\Framework\App\FrontController->getActionResponse()
#21 /magento/path/vendor/magento/framework/App/FrontController.php(147): Magento\Framework\App\FrontController->processRequest()
#22 /magento/path/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch()
#23 /magento/path/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent()
#24 /magento/path/vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(99): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
#25 /magento/path/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch()
#26 /magento/path/vendor/amasty/aminvisiblecaptcha/Plugin/Framework/App/FrontControllerInterface/ValidateCaptcha.php(124): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
#27 /magento/path/vendor/magento/framework/Interception/Interceptor.php(135): Amasty\InvisibleCaptcha\Plugin\Framework\App\FrontControllerInterface\ValidateCaptcha->aroundDispatch()
#28 /magento/path/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(75): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
#29 /magento/path/vendor/magento/framework/Interception/Interceptor.php(135): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch()
#30 /magento/path/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
#31 /magento/path/generated/code/Magento/Framework/App/FrontController/Interceptor.php(23): Magento\Framework\App\FrontController\Interceptor->___callPlugins()
#32 /magento/path/vendor/magento/framework/App/Http.php(116): Magento\Framework\App\FrontController\Interceptor->dispatch()
#33 /magento/path/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http->launch()
#34 /magento/path/pub/index.php(30): Magento\Framework\App\Bootstrap->run()
```

## Expected Behavior
- No error would be thrown
- Credit memos for all of the reported orders would be created with success

## Steps to Recreate the Issue
1. Create two or more orders that get flagged for review in Kount  (the Magento status should be `review`)
2. Open both orders in Kount
3. Mark both orders as **Decline** at *the same time*, clicking save
4. Wait ~1 minute for Kount to communicate back to Magento.

At this time you can observe:
- A `CRITICAL` error was thrown in `var/log/kount.log`
- No credit memos were created for all but the first order that was processed by the Kount ENS
- No refund transaction was made in Magento for all but the first order that was processed by the Kount ENS

**Comment by jcolas15** [comment]
Thank you, this has now been addressed in 4.3.17
